# -*- coding: utf-8 -*-
"""Copia de Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UjGK-o5EDW3cOJE8ESZFCt0t7qfWnzMN

**Taller 1**

No de identificación, Nombre, Apeliidos, Direccion, Telefono, Edad, Estado Civil, Numero de hijos, Estatura en centimetros, Fecha de contratación (dia/mes/año), Sueldo básico, Dias laborados.
"""

def saludar(nom):
  print("Hola "  + nom +  "   digita tus datos personales aquí por favor   ")

nombre = input("Digite su nombre o usuario:      ")
saludar(nombre)

while resp == "si" or resp == "s":
  
  Id = input("digite su numero de identificación   ")
  Nombre = input("digite su Nombre   ")
  Apellidos = input("digite sus Apellidos   ")
  Dirección = input("digite su Dirección   ")
  Telefono = input("digite su Telefono   ")
  Edad = input("digite su Edad    ")
  Estadocivil = input("digite su Estado civil   ")
  Numerodehijos = input("digite el Numero de hijos que tiene    ")
  Estatura = input("digite su estatura en centimetros    ")
  Fechadecontratación = input("digite su fecha de contratación    ")
  meslaborado = input("digite el mes a consultar")
  Diaslaborados = input("digite el numero de dias laborados a consultar    ")
  Sueldobasico = float(input("digite su sueldo basicó    "))
  if Sueldobasico <=2000000:
    sueldo = Sueldobasico
    bono = Sueldobasico *0.3
    total = sueldo + bono
    print("tiene bonificación del 30% sobre el sueldo base devengado = ${:,.0f} y el total a pagar es = ${:,.0f}".format(sueldo, total))
  else:
      print("no aplica para bonificación")
  resp = input("¿Desea diligenciar otros datos?")

"""**Taller 2**:

Dando continuidad con la primera entrega del proyecto, en esta oportunidad el estudiante debe realizar las siguientes validaciones utilizando la sentencia condicional IF.

Si el empleado es mayor de 55 años disfrutará de un bono de prepensión correspondiente al 5% de su sueldo básico.

Si el empleado es casado y tiene hijos se le otorgará un paseo cada diciembre

Si el sueldo básico está entre 1000000 y 1500000 tendrá una comisión del 2% sobre el valor del sueldo; Si el sueldo básico está entre 1500001 y 2000000 tendrá una comisión del 5% sobre el valor del sueldo; para todos los demás casos no habrá comisión.

Si el empleado trabajó más de 20 días al mes y su sueldo es menor a 1000000 tendrá derecho a un bono de alimentación.
"""

def saludar(nom):
  print("Hola "  + nom +  "   digita tus datos personales aquí por favor   ")

nombre = input("Digite su nombre o usuario:      ")
saludar(nombre)


while resp == "si" or resp == "s":
 empleado1 = float (input("digite su edad:   "))
 empleado1 =  int (input("digite estado civil:    "))
 sueldo = int (input("digite su sueldo:   "))
 mes = float (input( "bono alimenatción:    "))

 if empleado1 >=55:
   print("gana bono prepensión correspondiente al 5% de su sueldo básico")
 else:
    print("no aplica")

 if empleado1 in "casado con hijos":
   print("se le otorgará un paseo cada diciembre")
 else:
   print("no aplica")

 if sueldo <=1500000:
    sueldo = sueldo
    bono = sueldo *0.02
    total= bono + sueldo
    print("tiene bonificación del 2% sobre el sueldo base devengado = ${:,.0f} y el total a pagar es = ${:,.0f}".format(sueldo, total))
 else:
    print("no habrá comisión")

 if sueldo <= 2000000:
   sueldo = sueldo
   bono = sueldo *0.05
   total= bono + sueldo
   print("tiene bonificación del 5% sobre el sueldo base devengado = ${:,.0f} y el total a pagar es = ${:,.0f}".format(sueldo, total))
 else:
   print("no habrá comisión")

 if mes <=12:
   print("bono alimentación")
 else:
   print("no aplica")

 resp = input("¿Desea diligenciar otros datos?")

"""Se necesita un sistema que pida un sueldo de un
trabajador, si el sueldo es mayor a 655000, no tedrá
ninguna bonificación, pero si es menor tiene bonificación
del 4%. Al final se desea saber el total del sueldo con
o sin bonificación. Preguntar si desea ejecutar de nuevo
el programa con el ciclo while.
"""

resp = "aplica"
while resp == "aplica" or "si" or "si aplica" or "cuanto es la bonificación":

 sueldo = float (input("digite su sueldo"))

 if sueldo <= 655000:
   sueldo = sueldo
   bono = sueldo *0.04
   total= bono + sueldo
   print("tiene bonificación del 4% sobre el sueldo base devengado = ${:,.0f} y el total a pagar es = ${:,.0f}".format(sueldo, total))
 else:
   print("No tiene bonificación, el total a pagar es= ${:,.0f}".format(sueldo))

 resp = input("¿Desea cálcular otro sueldo?")

"""
Escribir un programa que pregunte al usuario su edad y
muestre por pantalla todos los años que ha cumplido
(desde 1 hasta su edad). ciclo for

"""

edad = int (input("digite su edad aquí: "))

for i in range(0,30,1):
  print(i, " x ", edad, " = ", edad * i)

acu = edad + i

 acu = edad
  print(f"El total de la suma de los años cumplidos es= {acu}")