# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qGy445A_xSPa_6QZ77YTMdV7z71a6dA7

**Taller 1**

No de identificación, Nombre, Apeliidos, Direccion, Telefono, Edad, Estado Civil, Numero de hijos, Estatura en centimetros, Fecha de contratación (dia/mes/año), Sueldo básico, Dias laborados.
"""

Id = input("digite su numero de identificación   ")
Nombre = input("digite su Nombre   ")
Apellidos = input("digite sus Apellidos   ")
Dirección = input("digite su Dirección   ")
Telefono = input("digite su Telefono   ")
Edad = input("digite su Edad    ")
Estadocivil = input("digite su Estado civil   ")
Numerodehijos = input("digite el Numero de hijos que tiene    ")
Estatura = input("digite su estatura en centimetros    ")
Fechadecontratación = input("digite su fecha de contratación    ")
meslaborado = input("digite el mes a consultar")
Diaslaborados = input("digite el numero de dias laborados a consultar    ")
Sueldobasico = float(input("digite su sueldo basicó    "))